<button class="btn btn-primary fb-btn" id="fb-button">Login With Facebook</button>

<script type="text/javascript">
    require(['jquery'], function($){
        $(function(){
            $('#fb-button').click(function(){
                $.ajax({
                    url: "https://graph.facebook.com/oauth/authorize",
                    header: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    },
                    dataType: "json",
                    type: "POST",
                    crossDomain: true,
                    data: { client_id: "111963142861596", redirect_uri: "http://magento.gloo/login/callback"}
                });
            });
        });
    });
</script>
